### ISSUE TITLE
No module named 'secretsanta'

### ISSUE THREAD

**Issue by ghost** [Axon000/secretsanta#2]
When I run:
`python3 secretsanta -i input.txt -o output.txt`

I get back:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "secretsanta/__main__.py", line 3, in <module>
    from secretsanta.app import app
```

I am not sure what I am doing wrong here.  Can you please advise?

**Comment by ghost** [comment]
If I run:
`python3 secretsanta -i input.txt -o output.txt`
I get less errors:
```
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from secretsanta.secretdraw import secretdraw
ModuleNotFoundError: No module named 'secretsanta'
```
